export const GENRES = {
  destacadas: "Destacadas",
  terror: "Terror",
  noir: "Cine negro",
  comedia: "Comedia",
  mudos: "Mudos",
  scifi: "Ciencia ficción",
  aventura: "Aventura",
  animacion: "Animación",
  autor: "Cine de autor",
  romance: "Romance",
  archivo: "Archivo",
} as const;

export type GenreId = keyof typeof GENRES;

export type License = "dominio-publico" | "cc-by" | "cc-by-sa";

export type Film = {
  id: string;
  archiveId: string;
  title: string;
  originalTitle?: string;
  year: number;
  runtime: number;
  director: string;
  country: string;
  language: string;
  genres: GenreId[];
  synopsis: string;
  license: License;
  quality: "SD" | "HD";
  featured?: boolean;
  hero?: boolean;
  poster?: string;
};

export const LICENSE_LABEL: Record<License, string> = {
  "dominio-publico": "Dominio público",
  "cc-by": "Creative Commons BY",
  "cc-by-sa": "Creative Commons BY-SA",
};

export const FILMS: Film[] = [
  {
    id: "night-of-the-living-dead",
    archiveId: "Night.Of.The.Living.Dead_1080p",
    title: "La noche de los muertos vivientes",
    originalTitle: "Night of the Living Dead",
    year: 1968,
    runtime: 96,
    director: "George A. Romero",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["destacadas", "terror"],
    synopsis:
      "Un grupo de extraños se atrinchera en una granja de Pennsylvania mientras los muertos caminan. Romero inventa aquí el zombi moderno: lento, político, sin consuelo. Estrenada sin aviso de copyright, es una de las obras maestras del terror que cualquiera puede ver en libertad.",
    license: "dominio-publico",
    quality: "HD",
    featured: true,
    hero: true,
    poster: "/posters/night-living-dead.jpg",
  },
  {
    id: "his-girl-friday",
    archiveId: "his_girl_friday",
    title: "Luna nueva",
    originalTitle: "His Girl Friday",
    year: 1940,
    runtime: 92,
    director: "Howard Hawks",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["destacadas", "comedia", "romance"],
    synopsis:
      "Un director de periódico intenta impedir que su ex reportera —y ex esposa— deje el oficio para casarse. Hawks dispara el diálogo a una velocidad que todavía marearía a cualquier serie actual. Screwball puro, inteligente y ferozmente moderno.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/his-girl-friday.jpg",
  },
  {
    id: "the-general",
    archiveId: "The_General_Buster_Keaton",
    title: "El maquinista de La General",
    originalTitle: "The General",
    year: 1926,
    runtime: 79,
    director: "Buster Keaton, Clyde Bruckman",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["destacadas", "mudos", "comedia", "aventura"],
    synopsis:
      "Un maquinista del Sur persigue el tren que le han robado —y, de paso, el amor de su vida. Keaton convierte una locomotora en compañera de baile. Una de las grandes películas de acción de la historia, rodada sin trucos digitales y con el cuerpo como único efecto especial.",
    license: "dominio-publico",
    quality: "HD",
    featured: true,
    poster: "/posters/the-general.jpg",
  },
  {
    id: "sintel",
    archiveId: "Sintel",
    title: "Sintel",
    year: 2010,
    runtime: 15,
    director: "Colin Levy / Blender Foundation",
    country: "Países Bajos",
    language: "Inglés",
    genres: ["destacadas", "animacion", "aventura", "autor"],
    synopsis:
      "Una joven guerrera recorre un mundo de hielo y ceniza en busca de una cría de dragón. Cortometraje abierto de la Blender Foundation, filmado con software libre y una ambición de cine de estudio. Prueba de que el cine gratuito también puede ser contemporáneo y bello.",
    license: "cc-by",
    quality: "HD",
    featured: true,
    hero: true,
    poster: "/posters/sintel.jpg",
  },
  {
    id: "carnival-of-souls",
    archiveId: "CarnivalofSouls",
    title: "Carnaval de almas",
    originalTitle: "Carnival of Souls",
    year: 1962,
    runtime: 78,
    director: "Herk Harvey",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["destacadas", "terror", "autor"],
    synopsis:
      "Tras un accidente de coche, una organista se muda a Utah y empieza a ver un hombre pálido que la espera en los espejos. Rodada con poco dinero y una intuición de pesadilla, es el eslabón entre el expresionismo y el cine independiente de horror.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/carnival-of-souls.jpg",
  },
  {
    id: "detour",
    archiveId: "Detour",
    title: "Desvío",
    originalTitle: "Detour",
    year: 1945,
    runtime: 68,
    director: "Edgar G. Ulmer",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["destacadas", "noir"],
    synopsis:
      "Un pianista de nightclub hace autostop hacia Los Ángeles y el destino le tiende una trampa de carretera. Ulmer rodó en seis días un noir esencial: fatalista, barato, perfecto. El cine negro reducido a su hueso.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/detour.jpg",
  },
  {
    id: "cabinet-caligari",
    archiveId: "DasKabinettdesDoktorCaligariTheCabinetofDrCaligari",
    title: "El gabinete del doctor Caligari",
    originalTitle: "Das Cabinet des Dr. Caligari",
    year: 1920,
    runtime: 74,
    director: "Robert Wiene",
    country: "Alemania",
    language: "Mudo",
    genres: ["destacadas", "terror", "mudos", "autor"],
    synopsis:
      "Un feriante hipnotiza a un sonámbulo para cometer crímenes en una ciudad pintada de pesadilla. Nacimiento del expresionismo alemán y de buena parte del cine de terror psicológico. Los decorados torcidos siguen siendo más modernos que muchos efectos de ahora.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/caligari.jpg",
  },
  {
    id: "phantom-of-the-opera",
    archiveId: "ThePhantomoftheOpera",
    title: "El fantasma de la ópera",
    originalTitle: "The Phantom of the Opera",
    year: 1925,
    runtime: 93,
    director: "Rupert Julian",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["terror", "mudos", "romance"],
    synopsis:
      "En los sótanos de la Ópera de París vive un hombre enmascarado que exige que Christine sea estrella. Lon Chaney construye una de las máscaras más famosas del cine mudo. Gótico, teatral y todavía capaz de cortar la respiración en el desenmascaramiento.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/phantom-opera.jpg",
  },
  {
    id: "nosferatu",
    archiveId: "Nosferatu_most_complete_version_93_mins.",
    title: "Nosferatu",
    originalTitle: "Nosferatu, eine Symphonie des Grauens",
    year: 1922,
    runtime: 93,
    director: "F. W. Murnau",
    country: "Alemania",
    language: "Mudo",
    genres: ["destacadas", "terror", "mudos", "autor"],
    synopsis:
      "El conde Orlok viaja de los Cárpatos a Wisborg y trae la peste. Adaptación no autorizada de Drácula que, por un azar legal, sobrevivió a la orden de destrucción. Murnau filma la sombra como si fuera un animal. El vampiro fundacional.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    hero: true,
    poster: "/posters/nosferatu.jpg",
  },
  {
    id: "my-man-godfrey",
    archiveId: "MyManGodfrey1936",
    title: "Al servicio de las damas",
    originalTitle: "My Man Godfrey",
    year: 1936,
    runtime: 94,
    director: "Gregory La Cava",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia", "romance"],
    synopsis:
      "Una heredera caprichosa «adopta» a un indigente como mayordomo y descubre que la alta sociedad es el verdadero circo. Screwball de la Depresión, con William Powell y Carole Lombard, que se ríe de los ricos sin perder el encanto.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/my-man-godfrey.jpg",
  },
  {
    id: "last-man-on-earth",
    archiveId: "TheLastManOnEarth_72",
    title: "El último hombre sobre la Tierra",
    originalTitle: "The Last Man on Earth",
    year: 1964,
    runtime: 86,
    director: "Ubaldo Ragona, Sidney Salkow",
    country: "Italia / Estados Unidos",
    language: "Inglés",
    genres: ["terror", "scifi"],
    synopsis:
      "Primera adaptación de la novela de Richard Matheson que luego sería Soy leyenda. Vincent Price recorre una Roma vaciada por la plaga, cazando de día y sitiado de noche. Ciencia ficción de duelo, previa a casi todo el cine postapocalíptico.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/last-man-on-earth.jpg",
  },
  {
    id: "sita-sings-the-blues",
    archiveId: "Sita_Sings_the_Blues",
    title: "Sita canta el blues",
    originalTitle: "Sita Sings the Blues",
    year: 2008,
    runtime: 82,
    director: "Nina Paley",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["destacadas", "animacion", "autor", "romance"],
    synopsis:
      "El Ramayana se cuenta como un musical de jazz, un cómic y una ruptura contemporánea. Nina Paley liberó la película bajo Creative Commons: color, humor, mitología y una banda sonora de Annette Hanshaw que parece llegada de 1929.",
    license: "cc-by-sa",
    quality: "HD",
    featured: true,
    poster: "/posters/sita-sings.jpg",
  },
  {
    id: "man-with-a-movie-camera",
    archiveId: "ChelovekskinoapparatomManWithAMovieCamera",
    title: "El hombre de la cámara",
    originalTitle: "Человек с киноаппаратом",
    year: 1929,
    runtime: 68,
    director: "Dziga Vertov",
    country: "Unión Soviética",
    language: "Mudo",
    genres: ["mudos", "autor"],
    synopsis:
      "Un día en una ciudad soviética filmado como manifiesto: sin actores, sin intertítulos, con el montaje como motor. Vertov enseña la máquina de ver. Sigue siendo una de las películas más vivas del siglo XX.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/man-with-camera.jpg",
  },
  {
    id: "big-buck-bunny",
    archiveId: "BigBuckBunny_124",
    title: "Big Buck Bunny",
    year: 2008,
    runtime: 10,
    director: "Sacha Goedegebure / Blender Foundation",
    country: "Países Bajos",
    language: "Sin diálogos",
    genres: ["animacion"],
    synopsis:
      "Un conejo pacífico decide vengarse de tres roedores matones. Corto abierto de Blender, rodado en alta definición, con una luz de pradera que parece de estudio Pixar. Ideal para ver la calidad que permite el cine libre contemporáneo.",
    license: "cc-by",
    quality: "HD",
    featured: true,
    poster: "/posters/big-buck-bunny.jpg",
  },
  {
    id: "house-on-haunted-hill",
    archiveId: "house_on_haunted_hill_ipod",
    title: "La casa de la colina encantada",
    originalTitle: "House on Haunted Hill",
    year: 1959,
    runtime: 75,
    director: "William Castle",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["terror"],
    synopsis:
      "Un millonario invita a cinco extraños a pasar la noche en una mansión a cambio de diez mil dólares. Vincent Price anfitrión, trampas, esqueletos y el sentido del espectáculo de Castle. Terror de feria, delicioso.",
    license: "dominio-publico",
    quality: "SD",
    poster: "/posters/haunted-hill.jpg",
  },
  {
    id: "most-dangerous-game",
    archiveId: "TheMostDangerousGame",
    title: "El juego más peligroso",
    originalTitle: "The Most Dangerous Game",
    year: 1932,
    runtime: 63,
    director: "Irving Pichel, Ernest B. Schoedsack",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["aventura", "terror"],
    synopsis:
      "Un cazador náufrago descubre que en la isla del conde Zaroff la presa es el hombre. Rodada en los mismos decorados de King Kong, es un thriller de 63 minutos sin grasa: selva, faros y una idea que el cine no ha dejado de repetir.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/most-dangerous-game.jpg",
  },
  {
    id: "a-star-is-born",
    archiveId: "AStarIsBorn",
    title: "Ha nacido una estrella",
    originalTitle: "A Star Is Born",
    year: 1937,
    runtime: 111,
    director: "William A. Wellman",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["romance", "autor"],
    synopsis:
      "Una chica de pueblo llega a Hollywood y un ídolo en decadencia la empuja hacia la luz. Primera versión sonora del mito: el estudio como fábrica de sueños y de ruina. Janet Gaynor y Fredric March, antes de Garland, Streisand y Lady Gaga.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/star-is-born.jpg",
  },
  {
    id: "passion-joan-of-arc",
    archiveId: "the-passion-of-joan-of-arc",
    title: "La pasión de Juana de Arco",
    originalTitle: "La Passion de Jeanne d'Arc",
    year: 1928,
    runtime: 82,
    director: "Carl Theodor Dreyer",
    country: "Francia",
    language: "Mudo",
    genres: ["mudos", "autor"],
    synopsis:
      "El proceso de Juana filmado casi solo en primeros planos. Falconetti entrega uno de los rostros más intensos del cine. Dreyer desnuda el juicio hasta dejar la piedra, la luz y una fe que duele. Obra capital del cine mudo.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    poster: "/posters/joan-of-arc.jpg",
  },
  {
    id: "the-stranger",
    archiveId: "TheStranger_0",
    title: "El extraño",
    originalTitle: "The Stranger",
    year: 1946,
    runtime: 95,
    director: "Orson Welles",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["noir"],
    synopsis:
      "Un agente federal rastrea a un criminal de guerra nazi escondido como profesor en un pueblo de Connecticut. Welles dirige y actúa: relojes, sombras, una torre gótica. Uno de los primeros filmes de Hollywood que mostró imágenes reales de los campos.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "scarlet-street",
    archiveId: "ScarletStreet",
    title: "Perversidad",
    originalTitle: "Scarlet Street",
    year: 1945,
    runtime: 102,
    director: "Fritz Lang",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["noir"],
    synopsis:
      "Un cajero mediocre, pintor aficionado, es devorado por una pareja de estafadores. Lang lleva el noir a un callejón sin salida moral. Edward G. Robinson, Joan Bennett y Dan Duryea en una de las obras más amargas del género.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "suddenly",
    archiveId: "suddenly",
    title: "De improviso",
    originalTitle: "Suddenly",
    year: 1954,
    runtime: 77,
    director: "Lewis Allen",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["noir"],
    synopsis:
      "Tres sicarios toman una casa con vista a las vías para asesinar al presidente. Frank Sinatra, lejos de la balada, interpreta a un veterano roto y letal. Thriller de un solo set, tenso como un tornillo.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "impact",
    archiveId: "impact",
    title: "Impacto",
    originalTitle: "Impact",
    year: 1949,
    runtime: 111,
    director: "Arthur Lubin",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["noir"],
    synopsis:
      "Un industrial sobrevive al intento de asesinato que tramó su esposa y desaparece en un pueblo de California. Noir de identidad falsa, moteles y una investigación que se vuelve contra el vivo. Pieza sólida de la serie B elevada.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "meet-john-doe",
    archiveId: "meet_john_doe",
    title: "Juan Nadie",
    originalTitle: "Meet John Doe",
    year: 1941,
    runtime: 122,
    director: "Frank Capra",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia", "romance", "autor"],
    synopsis:
      "Una periodista inventa a un hombre del pueblo que amenaza con suicidarse por las injusticias. El personaje se vuelve movimiento de masas y un magnate intenta comprarlo. Capra en su modo más político: fe en la gente, miedo a la demagogia.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "cyrano",
    archiveId: "Cyrano_DeBergerac",
    title: "Cyrano de Bergerac",
    year: 1950,
    runtime: 113,
    director: "Michael Gordon",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["romance", "aventura"],
    synopsis:
      "José Ferrer gana el Óscar como el espadachín de nariz imposible que escribe las cartas de otro. Versión estadounidense del clásico de Rostand: verso, duelos y una idea del amor que se niega a mostrarse. Teatro filmado con dignidad.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "as-you-like-it",
    archiveId: "AsYouLikeIt1936",
    title: "Como gustéis",
    originalTitle: "As You Like It",
    year: 1936,
    runtime: 96,
    director: "Paul Czinner",
    country: "Reino Unido",
    language: "Inglés",
    genres: ["comedia", "romance"],
    synopsis:
      "Laurence Olivier debuta en Shakespeare en la pantalla como Orlando, frente a Elisabeth Bergner. El bosque de Arden, los disfraces y el juego de géneros de la comedia pastoral. Una rareza elegante del cine británico de los treinta.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "little-princess",
    archiveId: "little_princess",
    title: "La princesita",
    originalTitle: "The Little Princess",
    year: 1939,
    runtime: 93,
    director: "Walter Lang",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["aventura", "romance"],
    synopsis:
      "Shirley Temple en Technicolor: una niña internada en Londres espera el regreso de su padre de la guerra de los bóers. Melodrama victoriano con canciones, desvanes y una fe obstinada. Cine familiar de estudio en su forma más pulida.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "gulliver",
    archiveId: "gullivers_travels1939",
    title: "Los viajes de Gulliver",
    originalTitle: "Gulliver's Travels",
    year: 1939,
    runtime: 76,
    director: "Dave Fleischer",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["animacion", "aventura"],
    synopsis:
      "El segundo largometraje de animación estadounidense, rival de Disney. Gulliver naufraga en Lilliput y dos reinos se pelean por una canción de boda. Los Fleischers aportan gags elásticos, rotoscopia y un trazo que no imita a Blancanieves.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "jungle-book",
    archiveId: "JungleBook",
    title: "El libro de la selva",
    originalTitle: "Rudyard Kipling's Jungle Book",
    year: 1942,
    runtime: 108,
    director: "Zoltan Korda",
    country: "Estados Unidos / Reino Unido",
    language: "Inglés",
    genres: ["aventura"],
    synopsis:
      "Sabu es Mowgli en una selva de estudio hiperreal, fotografiada por Lee Garmes y Nicolai Remisoff. No es el dibujo de Disney: es un cuento colonial de tesoros, tigres y fuego. Aventura clásica en Technicolor.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "royal-wedding",
    archiveId: "royal_wedding",
    title: "Bodas reales",
    originalTitle: "Royal Wedding",
    year: 1951,
    runtime: 93,
    director: "Stanley Donen",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia", "romance"],
    synopsis:
      "Fred Astaire y Jane Powell cruzan el Atlántico para actuar durante la boda de Isabel II. Incluye el número en el que Astaire baila en las paredes y el techo. Un musical que cayó en dominio público por un error de registro: suerte para nosotros.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "flying-deuces",
    archiveId: "TheFlyingDeuces",
    title: "Los legionarios",
    originalTitle: "The Flying Deuces",
    year: 1939,
    runtime: 69,
    director: "A. Edward Sutherland",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia"],
    synopsis:
      "Laurel y Hardy se alistan en la Legión Extranjera para curar un desengaño amoroso. Aviones, desiertos y el ballet torpe de la pareja más precisa de la comedia. Una de sus películas más libres de ver hoy.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "steamboat-bill-jr",
    archiveId: "SteamboatBillJr",
    title: "El héroe del río",
    originalTitle: "Steamboat Bill, Jr.",
    year: 1928,
    runtime: 71,
    director: "Charles Reisner, Buster Keaton",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["mudos", "comedia"],
    synopsis:
      "El hijo dandi de un capitán de vapor vuelve al Mississippi y sobrevive a un ciclón real. La fachada de casa que cae alrededor de Keaton —milímetros de error, muerte segura— es uno de los planos más célebres jamás rodados.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "sherlock-jr",
    archiveId: "sherlockjr1924_201909",
    title: "El moderno Sherlock Holmes",
    originalTitle: "Sherlock Jr.",
    year: 1924,
    runtime: 45,
    director: "Buster Keaton",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["mudos", "comedia"],
    synopsis:
      "Un projectionista se duerme y entra dentro de la película. Keaton inventa el metacine décadas antes de que tuviera nombre: cortes imposibles, persecuciones y un billar de gags. Cuarenta y cinco minutos de invención pura.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "battleship-potemkin",
    archiveId: "BattleshipPotemkin",
    title: "El acorazado Potemkin",
    originalTitle: "Броненосец Потёмкин",
    year: 1925,
    runtime: 75,
    director: "Sergei Eisenstein",
    country: "Unión Soviética",
    language: "Mudo",
    genres: ["mudos", "autor"],
    synopsis:
      "El motín de 1905 y la matanza en las escalinatas de Odesa. Eisenstein convierte el montaje en arma y en música. Todavía se cita en cada escuela de cine —y todavía funciona como thriller popular.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "lost-world",
    archiveId: "lost_world",
    title: "El mundo perdido",
    originalTitle: "The Lost World",
    year: 1925,
    runtime: 93,
    director: "Harry O. Hoyt",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["aventura", "scifi", "mudos"],
    synopsis:
      "Una expedición encuentra dinosaurios en una meseta amazónica. Willis O'Brien —antes de King Kong— anima criaturas fotograma a fotograma. Ciencia ficción muda, asombro de feria y el origen de todo el cine de monstruos.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "twenty-thousand-leagues",
    archiveId: "20000LeaguesUndertheSea",
    title: "Veinte mil leguas de viaje submarino",
    originalTitle: "20,000 Leagues Under the Sea",
    year: 1916,
    runtime: 105,
    director: "Stuart Paton",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["aventura", "scifi", "mudos"],
    synopsis:
      "Primera gran adaptación de Verne, con tomas submarinas reales de los hermanos Williamson. El Nautilus, los buzos y un océano que en 1916 parecía otro planeta. Arqueología del cine de aventuras.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "white-zombie",
    archiveId: "WhiteZombie",
    title: "El zombi blanco",
    originalTitle: "White Zombie",
    year: 1932,
    runtime: 67,
    director: "Victor Halperin",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["terror"],
    synopsis:
      "Bela Lugosi dirige un ingenio azucarero en Haití con obreros sin alma. Antes de Romero, el zombi era esclavitud y vudú. Ambiente de estudio, ojos vidriosos y una de las primeras películas de horror sonoro independientes.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "plan-9",
    archiveId: "plan-9-from-outer-space",
    title: "Plan 9 del espacio exterior",
    originalTitle: "Plan 9 from Outer Space",
    year: 1959,
    runtime: 79,
    director: "Edward D. Wood Jr.",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["scifi", "terror"],
    synopsis:
      "Extraterrestres resucitan a los muertos para evitar que la Tierra invente una bomba que destruya el universo. El «peor filme» es, visto con cariño, un acto de fe cinéfila. Wood, Vampira, Tor Johnson y Bela Lugosi en fragmentos póstumos.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "little-shop-of-horrors",
    archiveId: "The_Little_Shop_of_Horrors.mpeg",
    title: "La tiendita del horror",
    originalTitle: "The Little Shop of Horrors",
    year: 1960,
    runtime: 72,
    director: "Roger Corman",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia", "terror"],
    synopsis:
      "Un dependiente tímido cría una planta que habla y pide sangre. Corman la rodó en dos días. Jack Nicholson aparece como un masoquista del dentista. Comedia de serie B que después sería musical, aquí en su forma más sucia y rápida.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "dressed-to-kill",
    archiveId: "dressed_to_kill",
    title: "Vestida para matar",
    originalTitle: "Dressed to Kill",
    year: 1946,
    runtime: 72,
    director: "Roy William Neill",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["noir"],
    synopsis:
      "Última de las películas de Sherlock Holmes con Basil Rathbone y Nigel Bruce. Tres cajitas de música esconden las planchas de unos billetes robados. Misterio de estudio, niebla londinense de utilería y el placer de la fórmula bien ejecutada.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "secret-weapon",
    archiveId: "secret_weapon",
    title: "Sherlock Holmes y el arma secreta",
    originalTitle: "Sherlock Holmes and the Secret Weapon",
    year: 1943,
    runtime: 68,
    director: "Roy William Neill",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["noir", "aventura"],
    synopsis:
      "Holmes protege a un inventor suizo de bombas de la red de Moriarty en plena Segunda Guerra. La Universal actualizó a Conan Doyle para la propaganda aliada: sombras alemanas, códigos y el duelo eterno con el profesor.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "abraham-lincoln",
    archiveId: "abraham_lincoln",
    title: "Abraham Lincoln",
    year: 1930,
    runtime: 96,
    director: "D. W. Griffith",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["autor"],
    synopsis:
      "Griffith, ya en el sonoro, traza una biografía solemne de Lincoln desde Kentucky hasta Ford's Theatre. Walter Huston encarna al presidente como figura de granito. Documento de un pionero que intenta ponerse a la altura del mito nacional.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "reefer-madness",
    archiveId: "reefer_madness1938",
    title: "La locura del cannabis",
    originalTitle: "Reefer Madness",
    year: 1936,
    runtime: 66,
    director: "Louis J. Gasnier",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia"],
    synopsis:
      "Melodrama de propaganda que promete que un porro lleva al asesinato y a la locura. Hoy se ve como comedia involuntaria, pieza de museo de la histeria moral. Un clásico de culto que el dominio público devolvió a las sesiones de medianoche.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "tears-of-steel",
    archiveId: "Tears-of-Steel",
    title: "Tears of Steel",
    year: 2012,
    runtime: 12,
    director: "Ian Hubert / Blender Foundation",
    country: "Países Bajos",
    language: "Inglés",
    genres: ["animacion", "scifi"],
    synopsis:
      "Ámsterdam ocupada por robots, un grupo de resistencia y un amor que se graba en la memoria de una máquina. Corto abierto de Blender pensado para exhibir efectos visuales reales: live action, CG y una ciudad destruida con oficio de estudio.",
    license: "cc-by",
    quality: "HD",
    featured: true,
    hero: true,
  },
  {
    id: "elephants-dream",
    archiveId: "ElephantsDream",
    title: "Elephants Dream",
    year: 2006,
    runtime: 11,
    director: "Bassam Kurdali / Blender Foundation",
    country: "Países Bajos",
    language: "Inglés",
    genres: ["animacion", "autor"],
    synopsis:
      "Dos personajes recorren una máquina imposible, mitad fábrica y mitad sueño. Primer open movie de Blender: extraño, abstracto, fundacional. El cine generado por una comunidad que decidió no cerrar el archivo.",
    license: "cc-by",
    quality: "HD",
  },
  {
    id: "haxan",
    archiveId: "HaxanwithSpanishSubtitles",
    title: "Häxan",
    originalTitle: "Häxan: Witchcraft Through the Ages",
    year: 1922,
    runtime: 87,
    director: "Benjamin Christensen",
    country: "Suecia / Dinamarca",
    language: "Mudo",
    genres: ["destacadas", "terror", "mudos", "autor"],
    synopsis:
      "Un ensayo endemoniado sobre la brujería: de los grabados medievales a las posesiones, con un pie en el documental y otro en la pesadilla. Christensen filma el infierno como si fuera un estudio de antropología. Esta copia trae intertítulos en español.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
    hero: true,
  },
  {
    id: "trip-to-the-moon",
    archiveId: "le-voyage-dans-la-lune-1902-georges-melies",
    title: "Viaje a la luna",
    originalTitle: "Le Voyage dans la Lune",
    year: 1902,
    runtime: 13,
    director: "Georges Méliès",
    country: "Francia",
    language: "Mudo",
    genres: ["destacadas", "scifi", "mudos", "aventura"],
    synopsis:
      "Un proyectil con forma de cara, un ojo lunar y el cine aprendiendo a soñar. Méliès inventa el truco, el decorado pintado y la ciencia ficción popular en trece minutos que todavía parecen magia de feria.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "intolerance",
    archiveId: "Intolerance",
    title: "Intolerancia",
    originalTitle: "Intolerance",
    year: 1916,
    runtime: 197,
    director: "D. W. Griffith",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["mudos", "autor"],
    synopsis:
      "Cuatro épocas de persecución montadas en paralelo. Griffith responde a las críticas de El nacimiento de una nación con una máquina de montaje descomunal: Babilonia, Judea, Francia y un presente de linchamientos.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "the-golem",
    archiveId: "TheGolem_893",
    title: "El Golem",
    originalTitle: "Der Golem, wie er in die Welt kam",
    year: 1920,
    runtime: 85,
    director: "Paul Wegener, Carl Boese",
    country: "Alemania",
    language: "Mudo",
    genres: ["terror", "mudos", "autor"],
    synopsis:
      "En el ghetto de Praga, el rabino Loew modela un coloso de arcilla para proteger a su pueblo. Expresionismo, leyenda judía y el ancestro de todo el cine de monstruos empáticos.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "the-kid",
    archiveId: "Brzdac1921",
    title: "El chico",
    originalTitle: "The Kid",
    year: 1921,
    runtime: 68,
    director: "Charlie Chaplin",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["comedia", "mudos", "autor"],
    synopsis:
      "Charlot cría a un niño abandonado entre ventanas rotas y golpes de policía. Chaplin mezcla slapstick y melodrama sin pedir permiso. Jackie Coogan, seis años, y una de las parejas más precisas del mudo.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "phantom-carriage",
    archiveId: "ThePhantomCarriage",
    title: "La carreta fantasma",
    originalTitle: "Körkarlen",
    year: 1921,
    runtime: 93,
    director: "Victor Sjöström",
    country: "Suecia",
    language: "Mudo",
    genres: ["terror", "mudos", "autor"],
    synopsis:
      "Quien muere a medianoche de Año Nuevo debe conducir la carreta de la muerte. Sjöström se filma a sí mismo entre exposiciones dobles que todavía parecen contemporáneas. Bergman nunca dejó de citarla.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "safety-last",
    archiveId: "safety-last-1923",
    title: "El hombre mosca",
    originalTitle: "Safety Last!",
    year: 1923,
    runtime: 73,
    director: "Fred C. Newmeyer, Sam Taylor",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["comedia", "mudos"],
    synopsis:
      "Harold Lloyd cuelga del reloj sobre Los Ángeles. No es un truco de estudio: es un cuerpo real, una fachada real y el gag más famoso de la comedia americana. Vértigo convertido en risa.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "hunchback-1923",
    archiveId: "The_Hunchback_of_Notre_Dame",
    title: "El jorobado de Notre Dame",
    originalTitle: "The Hunchback of Notre Dame",
    year: 1923,
    runtime: 133,
    director: "Wallace Worsley",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["terror", "mudos", "romance"],
    synopsis:
      "Lon Chaney es Quasimodo en una Notre Dame reconstruida en Universal City. Maquillaje imposible, muchedumbres y el espectáculo del cine mudo cuando todavía competía con la catedral.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "thief-of-bagdad",
    archiveId: "ThiefOfBagdad1924",
    title: "El ladrón de Bagdad",
    originalTitle: "The Thief of Bagdad",
    year: 1924,
    runtime: 155,
    director: "Raoul Walsh",
    country: "Estados Unidos",
    language: "Mudo",
    genres: ["aventura", "mudos", "romance"],
    synopsis:
      "Douglas Fairbanks vuela en alfombra, pelea con monstruos y roba el corazón de una princesa. El cuento de Las mil y una noches en un decorado que parece soñado por un niño con presupuesto de estudio.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "faust-1926",
    archiveId: "Faust1926_201706",
    title: "Fausto",
    originalTitle: "Faust – Eine deutsche Volkssage",
    year: 1926,
    runtime: 106,
    director: "F. W. Murnau",
    country: "Alemania",
    language: "Mudo",
    genres: ["terror", "mudos", "autor"],
    synopsis:
      "Mefisto cubre el pueblo con sus alas. Murnau convierte el pacto fáustico en luz, humo y escala imposible. Emil Jannings como diablo teatral y una de las cimas visuales del expresionismo.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "metropolis",
    archiveId: "metropolis_202511",
    title: "Metrópolis",
    originalTitle: "Metropolis",
    year: 1927,
    runtime: 148,
    director: "Fritz Lang",
    country: "Alemania",
    language: "Mudo",
    genres: ["destacadas", "scifi", "mudos", "autor"],
    synopsis:
      "Arriba los jardines eternos; abajo las máquinas. Lang imagina la ciudad del siglo XX como un altar y una fábrica. Ciencia ficción fundacional, todavía más moderna que muchos futuros digitales.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "nothing-sacred",
    archiveId: "nothingsacred1937",
    title: "Nada sagrado",
    originalTitle: "Nothing Sacred",
    year: 1937,
    runtime: 77,
    director: "William A. Wellman",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["comedia", "romance"],
    synopsis:
      "Un periódico de Nueva York explota la «enfermedad terminal» de una chica de pueblo que está sana. Carole Lombard en Technicolor, screwball ácido sobre la prensa y el espectáculo de la piedad.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "angel-and-the-badman",
    archiveId: "angel_and_the_badman",
    title: "El ángel y el malo",
    originalTitle: "Angel and the Badman",
    year: 1947,
    runtime: 100,
    director: "James Edward Grant",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["aventura"],
    synopsis:
      "John Wayne es un pistolero herido que cae en una familia cuáquera. Western de conversión, caballos y una idea rara en el género: tal vez el revólver no sea la respuesta. Primera producción del propio Wayne.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "brain-that-wouldnt-die",
    archiveId: "the_brain_that_wouldnt_die",
    title: "El cerebro que no quería morir",
    originalTitle: "The Brain That Wouldn't Die",
    year: 1962,
    runtime: 82,
    director: "Joseph Green",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["terror", "scifi"],
    synopsis:
      "Un cirujano mantiene viva la cabeza de su prometida y busca un cuerpo nuevo en clubs de striptease. Serie B de laboratorio, monstruo en el armario y un clasicazo del horror involuntariamente cómico.",
    license: "dominio-publico",
    quality: "SD",
  },
  {
    id: "charade",
    archiveId: "charade-stanley-donen-1963-cary-grant-audrey-hepburn-comedie-policiere",
    title: "Charada",
    originalTitle: "Charade",
    year: 1963,
    runtime: 113,
    director: "Stanley Donen",
    country: "Estados Unidos",
    language: "Inglés",
    genres: ["destacadas", "comedia", "romance"],
    synopsis:
      "Audrey Hepburn y Cary Grant en un París de maletas, stamps y cadáveres. Donen firma el Hitchcock que Hitchcock no rodó. Cayó en dominio público por un error de registro: la comedia de suspense más elegante que se puede ver gratis.",
    license: "dominio-publico",
    quality: "SD",
    featured: true,
  },
  {
    id: "caminandes",
    archiveId: "Caminandes",
    title: "Caminandes",
    year: 2013,
    runtime: 8,
    director: "Pablo Vazquez / Blender Institute",
    country: "Países Bajos / Argentina",
    language: "Sin diálogos",
    genres: ["animacion"],
    synopsis:
      "Una llama patagónica contra vallas, pingüinos y meteoritos. Cortos abiertos de Blender, luz de estepa y humor físico. Prueba de que el cine libre también habla con acento del sur.",
    license: "cc-by",
    quality: "HD",
    featured: true,
  },
];

const byId = new Map(FILMS.map((f) => [f.id, f]));

export function getFilm(id: string) {
  return byId.get(id);
}

export function filmsByGenre(genre: GenreId) {
  return FILMS.filter((f) => f.genres.includes(genre));
}

export function featuredFilms() {
  return FILMS.filter((f) => f.featured);
}

export function heroFilms() {
  return FILMS.filter((f) => f.hero);
}

export function searchFilms(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return FILMS;
  return FILMS.filter((f) => {
    const hay = [
      f.title,
      f.originalTitle ?? "",
      f.director,
      f.year.toString(),
      f.country,
      f.language,
      ...f.genres.map((g) => GENRES[g]),
      "español",
      "subtitulos",
      "subtítulos",
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export function relatedFilms(film: Film, limit = 8) {
  const scored = FILMS.filter((f) => f.id !== film.id).map((f) => {
    const shared = f.genres.filter((g) => film.genres.includes(g)).length;
    return { f, shared };
  });
  scored.sort((a, b) => b.shared - a.shared || b.f.year - a.f.year);
  return scored.slice(0, limit).map((x) => x.f);
}

export function posterUrl(film: Film) {
  return film.poster ?? `https://archive.org/services/img/${film.archiveId}`;
}

export const BROWSE_ROWS: { id: GenreId; title: string }[] = [
  { id: "destacadas", title: "Para ver esta noche" },
  { id: "terror", title: "Terror y fantástico" },
  { id: "noir", title: "Cine negro" },
  { id: "comedia", title: "Comedia" },
  { id: "mudos", title: "Mudos que siguen vivos" },
  { id: "animacion", title: "Animación libre" },
  { id: "aventura", title: "Aventura" },
  { id: "autor", title: "Cine de autor" },
  { id: "scifi", title: "Ciencia ficción" },
  { id: "romance", title: "Romance" },
];
