/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeneroGenreRouteImport } from './routes/genero.$genre'
import { Route as PeliculaSlugRouteImport } from './routes/pelicula.$slug'
import { Route as VerSlugRouteImport } from './routes/ver.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneroGenreRoute = GeneroGenreRouteImport.update({
  id: '/genero/$genre',
  path: '/genero/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const PeliculaSlugRoute = PeliculaSlugRouteImport.update({
  id: '/pelicula/$slug',
  path: '/pelicula/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerSlugRoute = VerSlugRouteImport.update({
  id: '/ver/$slug',
  path: '/ver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/genero/$genre': typeof GeneroGenreRoute
  '/pelicula/$slug': typeof PeliculaSlugRoute
  '/ver/$slug': typeof VerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/genero/$genre': typeof GeneroGenreRoute
  '/pelicula/$slug': typeof PeliculaSlugRoute
  '/ver/$slug': typeof VerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/genero/$genre': typeof GeneroGenreRoute
  '/pelicula/$slug': typeof PeliculaSlugRoute
  '/ver/$slug': typeof VerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/lista'
    | '/login'
    | '/genero/$genre'
    | '/pelicula/$slug'
    | '/ver/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/lista'
    | '/login'
    | '/genero/$genre'
    | '/pelicula/$slug'
    | '/ver/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/lista'
    | '/login'
    | '/genero/$genre'
    | '/pelicula/$slug'
    | '/ver/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  GeneroGenreRoute: typeof GeneroGenreRoute
  PeliculaSlugRoute: typeof PeliculaSlugRoute
  VerSlugRoute: typeof VerSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genero/$genre': {
      id: '/genero/$genre'
      path: '/genero/$genre'
      fullPath: '/genero/$genre'
      preLoaderRoute: typeof GeneroGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelicula/$slug': {
      id: '/pelicula/$slug'
      path: '/pelicula/$slug'
      fullPath: '/pelicula/$slug'
      preLoaderRoute: typeof PeliculaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver/$slug': {
      id: '/ver/$slug'
      path: '/ver/$slug'
      fullPath: '/ver/$slug'
      preLoaderRoute: typeof VerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  GeneroGenreRoute: GeneroGenreRoute,
  PeliculaSlugRoute: PeliculaSlugRoute,
  VerSlugRoute: VerSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
